circle ci config comment out

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,106 +1,106 @@
-aliases:
-  # Caches
-  - &restore-yarn-cache
-    keys:
-      - v1-yarn-{{ .Branch }}-{{ checksum "website/yarn.lock" }}
-      # Fallback in case checksum fails
-      - v1-yarn-{{ .Branch }}-
+# aliases:
+#   # Caches
+#   - &restore-yarn-cache
+#     keys:
+#       - v1-yarn-{{ .Branch }}-{{ checksum "website/yarn.lock" }}
+#       # Fallback in case checksum fails
+#       - v1-yarn-{{ .Branch }}-
 
-  - &save-yarn-cache
-    paths:
-      - website/node_modules
-      - ~/.cache/yarn
-    key: v1-yarn-{{ .Branch }}-{{ checksum "website/yarn.lock" }}
+#   - &save-yarn-cache
+#     paths:
+#       - website/node_modules
+#       - ~/.cache/yarn
+#     key: v1-yarn-{{ .Branch }}-{{ checksum "website/yarn.lock" }}
 
-  # Filters
-  - &filter-only-master
-    branches:
-      only:
-        - master
+#   # Filters
+#   - &filter-only-master
+#     branches:
+#       only:
+#         - master
 
-defaults: &defaults
-  working_directory: ~/react-native-website
-  docker:
-    - image: circleci/node:8
+# defaults: &defaults
+#   working_directory: ~/react-native-website
+#   docker:
+#     - image: circleci/node:8
 
-version: 2
-jobs:
-  # Checkout and run yarn
-  checkout_code:
-    <<: *defaults
-    steps:
-      - checkout
+# version: 2
+# jobs:
+#   # Checkout and run yarn
+#   checkout_code:
+#     <<: *defaults
+#     steps:
+#       - checkout
 
-      - restore-cache: *restore-yarn-cache
-      - run:
-          name: Yarn Install
-          command: |
-            cd website
-            yarn install --no-progress --non-interactive --cache-folder ~/.cache/yarn
-      - save-cache: *save-yarn-cache
+#       - restore-cache: *restore-yarn-cache
+#       - run:
+#           name: Yarn Install
+#           command: |
+#             cd website
+#             yarn install --no-progress --non-interactive --cache-folder ~/.cache/yarn
+#       - save-cache: *save-yarn-cache
 
-      - persist_to_workspace:
-          root: .
-          paths: .
+#       - persist_to_workspace:
+#           root: .
+#           paths: .
 
-  # Tests website
-  test_website:
-    <<: *defaults
-    working_directory: ~/react-native-website/website
-    steps:
-      - attach_workspace:
-          at: ~/react-native-website
-      - run: yarn ci-check
-      - run: yarn test
-      - run:
-          name: Check for missing index.html (build errors)
-          command: |
-            if [ ! -f build/react-native/index.html ]; then
-              exit 1;
-            fi
+#   # Tests website
+#   test_website:
+#     <<: *defaults
+#     working_directory: ~/react-native-website/website
+#     steps:
+#       - attach_workspace:
+#           at: ~/react-native-website
+#       - run: yarn ci-check
+#       - run: yarn test
+#       - run:
+#           name: Check for missing index.html (build errors)
+#           command: |
+#             if [ ! -f build/react-native/index.html ]; then
+#               exit 1;
+#             fi
 
-  # Deploys website
-  deploy_website:
-    <<: *defaults
-    working_directory: ~/react-native-website/website
-    steps:
-      - attach_workspace:
-          at: ~/react-native-website
-      - run:
-          name: Install Dependencies
-          command: sudo apt install rsync
-      - run:
-          name: Build and Deploy Static Website
-          command: |
-            if [[ $CIRCLE_PROJECT_USERNAME == "facebook" && -z $CI_PULL_REQUEST && -z $CIRCLE_PR_USERNAME ]]; then
-              git config --global user.email "reactjs-bot@users.noreply.github.com"
-              git config --global user.name "Website Deployment Script"
-              echo "machine github.com login reactjs-bot password $GITHUB_TOKEN" > ~/.netrc
-              echo "Deploying website..."
-              GIT_USER=reactjs-bot CIRCLE_PROJECT_REPONAME=react-native yarn run publish-gh-pages
-            else
-              echo "Skipping deploy."
-            fi
+#   # Deploys website
+#   deploy_website:
+#     <<: *defaults
+#     working_directory: ~/react-native-website/website
+#     steps:
+#       - attach_workspace:
+#           at: ~/react-native-website
+#       - run:
+#           name: Install Dependencies
+#           command: sudo apt install rsync
+#       - run:
+#           name: Build and Deploy Static Website
+#           command: |
+#             if [[ $CIRCLE_PROJECT_USERNAME == "facebook" && -z $CI_PULL_REQUEST && -z $CIRCLE_PR_USERNAME ]]; then
+#               git config --global user.email "reactjs-bot@users.noreply.github.com"
+#               git config --global user.name "Website Deployment Script"
+#               echo "machine github.com login reactjs-bot password $GITHUB_TOKEN" > ~/.netrc
+#               echo "Deploying website..."
+#               GIT_USER=reactjs-bot CIRCLE_PROJECT_REPONAME=react-native yarn run publish-gh-pages
+#             else
+#               echo "Skipping deploy."
+#             fi
 
-workflows:
-  version: 2
+# workflows:
+#   version: 2
 
-  # Tests run on master and on forks
-  tests:
-    jobs:
-      - checkout_code
+#   # Tests run on master and on forks
+#   tests:
+#     jobs:
+#       - checkout_code
 
-      # Test website
-      - test_website:
-          requires:
-            - checkout_code
+#       # Test website
+#       - test_website:
+#           requires:
+#             - checkout_code
 
-  # If we are on master, deploy docs
-  deploy:
-    jobs:
-      - checkout_code:
-          filters: *filter-only-master
+#   # If we are on master, deploy docs
+#   deploy:
+#     jobs:
+#       - checkout_code:
+#           filters: *filter-only-master
 
-      - deploy_website:
-          requires:
-            - checkout_code
+#       - deploy_website:
+#           requires:
+#             - checkout_code
